title = "Backtestd documentation"
theme = "hugo-onyx-theme"

contentdir = "content"

disableFastRender = true        # Hugo 0.30

pygmentsCodeFences = true       # This applies to Chroma too.
pygmentsUseClasses = true       # This applies to Chroma too.

enableEmoji = true

disableKinds = ["taxonomy", "taxonomyTerm"]
LanguageCode = "en-us" # Used in RSS generation

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # This is *necessary* for ox-hugo to work well with Hugo 0.60.0+

[Author]
  name = "Stefan Lendl"

# [caches]
#   [caches.getjson]
#     dir = ":cacheDir/:project"
#     maxAge = "1m" # Disable caching getJSON data

# [Permalinks]
#   # post = "/:year/:month/:title/"
#   # Below, we have
#   #   foo = "bar"
#   # where foo = section name without double quotes for which we want to have
#   # the custom permalinks. If foo is 'posts', it will apply to content in
#   # content/posts/ dir. The "bar" portion is how you want the links to look.
#   # https://gohugo.io/content-management/urls/#permalink-configuration-values
#   doc = "/doc/:filename/"
#   test = "/test/:slug/"

[params]
  name = "Backtestd"

  description = "Documentation for the automated optimization pipeline"

  # Go date formats: https://golang.org/pkg/time/#pkg-constants
  dateform = "Mon Jan 2, 2006"

  github_user = "stfl"
  github_repo = "backtestd-doc"
  github_banner = false

#  images = ["/favicon-196x196.png"] # Used in twitter_cards.html partial

  custom_css = [ # Chroma GitHub theme
                 "css/github_chroma.css" # Needs pygmentsUseClasses to be true
               ]
  custom_css_absolute = [ # Iosevka fonts
                          # "https://cdn.rawgit.com/kaushalmodi/iosevka-mirror/v1.13.2/iosevka.css"
                        ]
  custom_js  = []

  # favicon = "favicon.ico"




[params.sidebar]
  logo = "favicon.ico"

  github_button  = true
  travis_button  = false
  codecov_button = false
  gratipay = ""

  # Mon Sep 04 23:55:36 EDT 2017 - kmodi
  # Disable this option for now.. but seems to be useful in future
  show_relations = false

[params.footer]
  copyright = "Stefan Lendl"
  show_powered_by = true
