#+title: Jupyter Server Setup
#+hugo_base_dir: ../hugo
#+hugo_section: articles

#+BEGIN_QUOTE
The [[https://jupyter.org/][Jupyter]] Notebook is an open-source web application that allows you to create and share documents that contain live code, equations, visualizations and narrative text. Uses include: data cleaning and transformation, numerical simulation, statistical modeling, data visualization, machine learning, and much more.
#+END_QUOTE

* Anaconder LXC Container

The Anaconda Container needs to be priviliged to enable CIFS mount from
the Win10 vm.

** user account
:PROPERTIES:
:CUSTOM_ID: user-account
:END:

#+BEGIN_SRC sh
adduser condor
usermod -aG sudo condor
#+END_SRC

** setup smb cifs mount
:PROPERTIES:
:CUSTOM_ID: setup-smb-cifs-mount
:ID:       4067a08c-2175-4a17-bf9d-5e1a580c0f8a
:END:

#+BEGIN_SRC sh
mkdir /mnt/workdir
mkdir /mnt/backtestd
#+END_SRC

manually mount the workdir and apply directory permissions

on dev PC:
#+BEGIN_SRC bash
sudo mount -vv -t cifs -o -o defaults,_netdev,username=Stefan,password=***,uid=2000,gid=2000,dir_mode=0755,file_mode=0644 \
    //192.168.12.61/users/Stefan/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/ /mnt/workdir
#+END_SRC

from Anaconda host (/note uid/)
#+BEGIN_SRC bash
sudo mount -vv -t cifs -o -o defaults,_netdev,username=Stefan,password=***,uid=1000,gid=1000,dir_mode=0755,file_mode=0644 \
    //192.168.12.61/users/Stefan/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/ /mnt/workdir
#+END_SRC

automount with fstab. assing the condor user to the directory and allow write
permissions...

~/etc/fstab~
#+BEGIN_src fstab /etc/fstab
//192.168.12.61/users/Stefan/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/ /mnt/workdir cifs    defaults,_netdev,username=Stefan,password=***,uid=1000,gid=1000,dir_mode=0755,file_mode=0644,noauto,x-systemd.automount,x-systemd.mount-timeout=300          0       0

//192.168.12.61/users/Stefan/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Indicators/backtestd /mnt/backtestd      cifs    defaults,_netdev,username=Stefan,password=***,uid=1000,gid=1000,dir_mode=0755,file_mode=0644,noauto,x-systemd.automount,x-systemd.mount-timeout=300          0       0
#+END_src

-> /update password/

check [[file:../20200830101618-infrastructure.org][Infrastructure Description]] for IP address of MT5 Master

** PVE boot order to make smb mount work at boot

- MT5 (Master|Agents) /order=1/
- anaconda LXC /order=3,up=600/

*** TODO test up-delay

** install anaconda
:PROPERTIES:
:CUSTOM_ID: install-anaconda
:END:

login as condor

[[https://www.digitalocean.com/community/tutorials/how-to-install-the-anaconda-python-distribution-on-ubuntu-20-04-de][Installieren der Anaconda Python-Distribution unter Ubuntu 20.04 | DigitalOcean]]

#+BEGIN_SRC sh
curl https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh --output anaconda.sh
sha256sum anaconda.sh

# 2b9f088b2022edb474915d9f69a803d6449d5fdb4c303041f60ac4aefcc208bb  anaconda.sh

bash anaconda.sh
#+END_SRC

** Running Jupyter Lab Server

[[https://jupyter-notebook.readthedocs.io/en/stable/public_server.html][Running a notebook server]]

*** Auto-start with systemd

#+BEGIN_SRC conf
[Unit]
After=network.service
After=mnt-backtestd.mount
After=mnt-reports.mount

[Service]
User=condor
ExecStart=/home/condor/anaconda3/bin/jupyter lab --port=8888 --no-browser --ip=0.0.0.0
WorkingDirectory=/home/condor/jupyter

[Install]
WantedBy=default.target
#+END_SRC

#+BEGIN_SRC bash
sudo systemctl daemon-reload
sudo systemctl enable --now jupyter-lab
#+END_SRC

~http://192.168.12.4:8888/?token=<token>~

*** TODO Password setup


* deploy notebook
:PROPERTIES:
:CUSTOM_ID: deploy-notebook
:END:

** Dependencies
#+BEGIN_SRC sh
sudo apt install git build-essential
pip install nbdiff
#+END_SRC

** Deploy

#+BEGIN_SRC bash
git clone ...
#+END_SRC


* deploy backtestd.py

#+BEGIN_SRC bash
poetry
#+END_SRC
